# Generated by Django 3.0.3 on 2020-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listmatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaguename', models.CharField(max_length=900)),
                ('opponent_one', models.CharField(max_length=100)),
                ('opponent_two', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('pastscore_opone', models.IntegerField()),
                ('pastscore_optwo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='livematches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaguename', models.CharField(max_length=900)),
                ('opponent_one', models.CharField(max_length=100)),
                ('opponent_two', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('livescore_opone', models.IntegerField()),
                ('livescore_optwo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='upcomingmatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaguename', models.CharField(max_length=900)),
                ('opponent_one', models.CharField(max_length=100)),
                ('opponent_two', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('odds_one', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_two', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
